language: java
jdk:
- oraclejdk8
notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/48597b0f75dd571734bc
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always   # options: [always|never|change] default: always
  email:
    recipients:
      - jmurekezi@gmail.com
      - jmurekezi@gmail.com
    on_success: always #[always|never|change] # default: change
    on_failure: always # [always|never|change] # default: always

after_success:
  - codecov
branches:
  only:
  - master
